apiVersion: v1
kind: Service
metadata:
  name: django-api-service
  namespace: staging
spec:
  type: NodePort
  selector:
    app: django-api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30081  # Accessible via :30081