apiVersion: v1
kind: Service
metadata:
  name: laravel-api-service
  namespace: staging
spec:
  type: NodePort
  selector:
    app: laravel-api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30082  # Accessible via :30082