apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-api
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-api
  template:
    metadata:
      labels:
        app: laravel-api
    spec:
      containers:
      - name: laravel-api
        image: mohamedshehata18/laravel-api:staging-latest
        ports:
        - containerPort: 8000
        env:
        - name: LARAVEL_ENV
          value: "development"