apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-api
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-api
  template:
    metadata:
      labels:
        app: django-api
    spec:
      containers:
      - name: django-api
        image: mohamedshehata18/laravel-api:prod-18d7b2ea036148c4f16e364ee0ff13c135374a80
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "simple_django_backend.settings"