apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-api
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-api
  template:
    metadata:
      labels:
        app: django-api
    spec:
      containers:
      - name: django-api
        image: mohamedshehata18/laravel-api:prod-1a82fbb82584c173c514ba0b32c06a3dc08c281c
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "simple_django_backend.settings"