apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-api
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-api
  template:
    metadata:
      labels:
        app: django-api
    spec:
      containers:
      - name: django-api
        image: mohamedshehata18/django-api:dev-latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "simple_django_backend.settings"